### ISSUE TITLE
Need to add document identifiers and dates to index.adoc

### ISSUE THREAD

**Issue by bradh** [jyutzler/geopackage-related-tables#13]
This is a tracker issue for editorial stuff such as obtaining the document identifier.

**Comment by jyutzler** [comment]
Part of my job over the holidays is to migrate this from an extension template into the OGC standard template (as was done for the [tiled gridded coverage extension](http://www.geopackage.org/17-066r1.html)). I also need to ensure that there is a web accessible version of the document, preferably one that is auto-generated when any changes are made.

Stay tuned.

**Comment by jyutzler** [comment]
Marking this closed as we have a document template now, including document number etc.
