### ISSUE TITLE
Requirements Class 1 and 2 is confusing

### ISSUE THREAD

**Issue by bradh** [jyutzler/geopackage-related-tables#14]
In the HTML rendering, there are two requirements classes ([6.1](http://www.geopackage.org/18-000.html#_requirement_class_1_table_definitions) and [6.2](http://www.geopackage.org/18-000.html#_requirement_class_2_table_values). The distinction between table definitions and table values seems a bit too subtle for there to be requirements classes.

That seems likely to cause confusion (e.g. with conformance levels) and would be better handled as a single tier.

**Comment by jyutzler** [comment]
https://github.com/jyutzler/geopackage-related-tables/commit/a43bb4b8c8bd7732a63fa4d041965b47433bd3d2
