### ISSUE TITLE
Missing reference for OGC 06-121r8

### ISSUE THREAD

**Issue by bradh** [jyutzler/geopackage-related-tables#15]
We refer to this document in the [Terms and Definitions](http://www.geopackage.org/18-000.html#_terms_and_definitions) so it should be in the [References](http://www.geopackage.org/18-000.html#_references) section

**Comment by jyutzler** [comment]
Fixed by https://github.com/jyutzler/geopackage-related-tables/commit/6e3a486f58b103d1e545d1bbb6362f105ab20349
