### ISSUE TITLE
Reconsider allowing views for table definitions

### ISSUE THREAD

**Issue by bradh** [jyutzler/geopackage-related-tables#16]
http://www.geopackage.org/18-000.html#_extended_relations_table says "A GeoPackage that complies with this extension SHALL contain a gpkgext_relations table or view as per Extended Relations Table Definition and Extended Relations Table Definition SQL (Normative)."

The use of a view is problematic because the table definition is normative (i.e. it'll fail validation if it doesn't match exactly given the historical ETS practice) and that views aren't usually updateable (can be done, but isn't required). Not being able to update the view is contrary to adding data, or modifying relationships.

Suggest requiring it to be a table, disallowing use of views.

**Comment by jyutzler** [comment]
Fixed by https://github.com/jyutzler/geopackage-related-tables/commit/f4433ba233c7ed99982ec07893460c098806b0d7
