### ISSUE TITLE
Consider adding SQL constraints for cardinality column

### ISSUE THREAD

**Issue by bradh** [jyutzler/geopackage-related-tables#19]
The `cardinality` column has a limited range of values. That could be enforced by SQL triggers as we have for the [base spec](http://www.geopackage.org/spec/#_trigger_definition_sql_informative).

**Comment by rcasscslt** [comment]
Something like?:

```sql
CREATE TABLE 'gpkgext_relations' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  base_table_name TEXT NOT NULL,
  base_primary_column TEXT NOT NULL DEFAULT 'id',
  attribute_table_name TEXT NOT NULL,
  attribute_primary_column TEXT NOT NULL DEFAULT 'id',
  relation_name TEXT NOT NULL,
  mapping_table_name TEXT UNIQUE,
  cardinality TEXT NOT NULL CHECK( cardinality in ('many-to-many','many-to-one','one-to-many'))
 );```

**Comment by bradh** [comment]
Yep. 

Ref: `mapping_table_name` not null PR at #18.

**Comment by jyutzler** [comment]
Fixed by https://github.com/jyutzler/geopackage-related-tables/commit/2f4e5c0a0c8a6c3ecd2f84497b5c1de3066677d6
