### ISSUE TITLE
Decide if mapping_table_name should be unique

### ISSUE THREAD

**Issue by bradh** [jyutzler/geopackage-related-tables#20]
http://www.geopackage.org/18-000.html#_extended_relations_table currently has a "yes?" for the uniqueness of the `mapping_table_name` column value. 

Suggest it should be unique (remove question mark).

**Comment by rcasscslt** [comment]
I'm Ok with that.  I think there is  potential confusion from trying to map multiple relations in a single table - liitle to be gained.
