### ISSUE TITLE
Decide if we have a dependency on tiles

### ISSUE THREAD

**Issue by bradh** [jyutzler/geopackage-related-tables#26]
https://github.com/jyutzler/geopackage-related-tables/blob/master/standard/requirements/requirements_class_Table_Definitions.adoc declares a dependency on the tiles part of GPKG 1.2, which doesn't seem necessary.

**Comment by jyutzler** [comment]
Well, we haven't tested it out but in theory it doesn't have to be linked to tiles. For example, someone could associate a UTFGrid with a tile. (Hey, that might actually be a good idea. Someone was asking me for UTFGrid a while back and I didn't have a good answer at the time.)

This part about the requirements dependency is a bit pedantic anyway. I'm not sure anyone really cares. I guess I can ask around of what the intent of this is supposed to be.

**Comment by bradh** [comment]
Should that be "doesn't have to be linked to features"?

I'm not saying whether we could, just thinking about compliance testing. A compliant producer (equally, consumer) of related tables doesn't need to be able to produce (equally, consume) tiles to work with what we currently have in the spec. So referring to that part of the base spec doesn't seem necessary.

**Comment by bradh** [comment]
I think we allow tiles, so this is noise.
