### ISSUE TITLE
Decide if a geopackage with related_table extension must contain a mapping

### ISSUE THREAD

**Issue by bradh** [jyutzler/geopackage-related-tables#28]
Equivalently, does `gpkgext_relations` need to contain at least one row?

I don't see anything in the spec that requires there to be any such mapping, only what happens if there is one.

I have a weak preference for requiring at least one mapping if the geopackage declares related_tables as an extension.

**Comment by tabinfl** [comment]
I think an empty `gpkgext_relations` is OK, as may be in the case when one creates a gpkg file that will have related table data added to it but does not yet, or if all related table attributes are removed from a GeoPackage. Might clarify that the `gpkgext_relations` table must exist, though (thinking an SQL query that returns empty shouldn't break code, but a query against a missing table will).

**Comment by rcasscslt** [comment]
Agreed. There should be at least one relation before registering the 
extension.

**Comment by jyutzler** [comment]
I think I disagree with this, but it is not a strong opinion. We allow an empty "template" GeoPackage that has no data in it.

**Comment by bradh** [comment]
Brad to propose a PR for this.

**Comment by bradh** [comment]
Resolved by #35.
