### ISSUE TITLE
Review Applicability in introduction

### ISSUE THREAD

**Issue by bradh** [jyutzler/geopackage-related-tables#41]
> Applicability: This extension defines a relationship between feature tables and aspatial tables that hold related content (e.g., media).

This may not be quite broad enough - different types of relationships, different tables holding different data.

**Comment by jyutzler** [comment]
I agree this can be worded better but if I had a better wording, I would have used it. I'm open to suggestions.

**Comment by jyutzler** [comment]
Ashley is going to work on updated text for this and put it both here and in the ER.

**Comment by ashleyholt** [comment]
How about:

Applicability: This extension defines all degrees of relationships between feature tables and tables that hold related content, including multimedia, simple attributes, and other features.

**Comment by bradh** [comment]
I like it. Possibly without the "all degrees of" part, so it would read: "This extension defines relationships between feature tables and tables that hold related content, including multimedia, simple attributes, and other features."

**Comment by bradh** [comment]
Fixed by #56.
